package ch.kalunight.zoe.model;

public enum Objective {
  MASTERY_POINT,
  MASTERY_EVERYONE_START_FROM_0,
  MASTERY_POINT_SPECIFIC_CHAMP,
  MASTERY_POINT_START_FROM_0_SPECIFIC_CHAMP,
  RANK,
  RANK_PROGRESSION,
  AVERAGE_KDA
}
